#!/usr/bin/ruby

require_relative 'drawing_window'

require 'rcr/easy'
require 'rcr/data/image'

# TODO: "make new sample" button?

module RCRExamples
	class ClassifyLetter
		class Window < RCRExamples::DrawingWindow
			include RCR::Logging

			def initialize(classifier)
				super(classifier)
				@letter = nil

				@area.overlays << self
			end

			def add_box_controls(box)
				letter_label = Gtk::Label.new
				letter_label.use_markup = true

				button = Gtk::Button.new("Classify")
				button.signal_connect :clicked do
					@drawn_letter = @area.drawn_letter

					best_5 = @area.drawn_letter_variants.to_a.sort_by { |pair| pair[1] }.reverse.take(5)
					best_5_text = best_5.map { |pair| "#{pair[0]} (%.2f)" % pair[1] }.join("; ")

					log "[#@drawn_letter] (best 5 candidates: #{best_5_text})"
					letter_label.label = "<b>#@drawn_letter</b> (best 5 candidates: #{best_5_text})"

					@area.queue_draw_area 0, 0, @area.allocation.width, @area.allocation.height
				end
				box.pack_end(button, false, false)
				box.pack_end(letter_label, false, false)
				button.show
				letter_label.show
			end

			def title
				"Letter classifier"
			end

			def draw_on_area(area)
				if @letter
					layout = Pango::Layout.new Gdk::Pango.context
					layout.font_description = Pango::FontDescription.new('Sans 14')
					layout.text = "Detected: #@letter"
					area.window.draw_layout(area.style.fg_gc(Gtk::STATE_NORMAL), 30, window_height + 20, layout)
				end
			end
		end

		def initialize(classifier)
			@classifier = classifier
		end

		def run
			Gtk.init
			window = RCRExamples::ClassifyLetter::Window.new(@classifier)
			window.enable_logging = true
			Gtk.main
		end
	end
end

classifier = RCR.build_letter_classifier
gui = RCRExamples::ClassifyLetter.new(classifier)
gui.run
