#!/usr/bin/ruby -w

require 'rcr/word-segmentator'
require 'rcr/data/image'
require 'rcr/data/segmentation'

raise unless (1..2).include? ARGV.length

inp, inp_adjust = "", ""

if ARGV.length == 2
	puts "loading: #{ARGV}"
	inp, inp_adjust = *ARGV
elsif ARGV.length == 1
	inp, inp_adjust = File.join(ARGV.first, "data.png"), File.join(ARGV.first, "divided.png")
end

image = RCR::Data::Image.load(inp)
image_adjust = RCR::Data::Image.load(inp_adjust)

segm = RCR::Data::Segmentation.new(image, RCR::WordSegmentator.load_segmentation_from_sample(image, image_adjust))
segm.draw_on_image!(image)
image.save("check_me.png")
