#!/usr/bin/ruby -w

require 'rcr/config'

require 'rcr/letter-classifier/neural'
classifier = RCR::LetterClassifier::Neural.load(RCR::Config.letter_classifier_path)

if ARGV[0] == "-i" || ARGV[0] == "--interactive" || ARGV.empty?
	require 'rcr/gui/classify-letter'
	gui = RCR::GUI::ClassifyLetter.new(classifier)
	gui.run
else
	require 'rcr/data/image'
	result = classifier.classify(RCR::Data::Image.load(ARGV[0]))
	puts "Classifier result: #{result}"
end
